name: get_daily_stats

on:
  workflow_dispatch
  #schedule:
  #  - cron: '0 20 * * *'
  
env:
  PGHOST: '${{secrets.PGHOST}}'
  PGDATABASE: '${{secrets.PGDATABASE}}'
  PGUSER: '${{ secrets.PGUSER}}'
  PGPASSWORD: '${{ secrets.PGPASSWORD}}'

jobs:
    run-script:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install
  
      - name: Run stats script
        run: python postings_parser/analytics/daily_stats.py   # Replace with the actual path to your script
