name: delete-removed-scrapy-postings

on:
    workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.scrapy --tag postings_parser_scrapy_image


    - name: Run the Container
      id: run
      run: |
        docker run -p 5432:5432 -e PGHOST='${{secrets.PGHOST}}' \
        -e PGDATABASE='${{secrets.PGDATABASE}}' \
        -e PGUSER='${{ secrets.PGUSER}}' \
        -e PGPASSWORD='${{ secrets.PGPASSWORD}}' \
        -e RUN_SELENIUM='false' \
        -e RUN_SCRAPY='true' \
        -e ACTION_TYPE='deleter' \
        postings_parser_scrapy_image